### PR TITLE
Add component comments

### PR DESCRIPTION
**Pull request by andrewdamelio**
### Add component comments - 🚨🚨WIP 🚨🚨
 Adding the following comment and PropType syntax to our stateless components.
- [x] Counter.js
- [ ] LoginForm.js
- [x] LoginModal.js
- [x] Navigator.js
- [x] NavigatorItem.js
```js
import React, { PropTypes }  from 'react';
/**
 * A React component that displays a greeting.
 *
 * Example usage:
 *
 * ```
 * renderExample() {
 *   return <Example type="cool">;
 * }
 * ```
 */
const Example = ({ type }) => {
  return (
    <h1>{ type + ' ' + 'Hello World' }</h1>
  );
};
Example.displayName = 'Example';
Example.propTypes = {
  /**
   * The type of greeting. The default is 'not-cool'.
   */
  type: PropTypes.oneOf(['cool', 'not-cool']),
  /**
   * If true, it's made sarcastic.
   */
  meta: PropTypes.bool,
};
Example.defaultProps = {
  type: 'not-cool',
};

export default Example;

```

### CODE REVIEW

**Comment by andrewdamelio** [comment]
@bertrandk  @neilff

**Comment by ramanpreetnara** [comment]
The JSDoc [@example](http://usejsdoc.org/tags-example.html) will give us pretty highlighting for our comments on Github. Is there any reason why we're doing 'Example usage:' instead?

**Comment by andrewdamelio** [comment]
@ramanpreetnara I believe this is all to utilize https://github.com/reactjs/react-docgen, @neilff @bertrandk is that correct?

**Comment by bertrandk** [comment]
Yeah, we don't expect to parse it using JSDocs. That said, I'm not entirely against using any pragma tags as long as it doesn't inhibit readability or increase documentation efforts. We'll be using a custom resolver anyways and this wouldn't be hard for me to add.

**Pull request closed without merging**
