### PR TITLE
fix: add package dependency removed in #127

### PR DESCRIPTION
**Pull request by mhazy**
Fixed my bad PR

### CODE REVIEW

**Comment by JaKXz** [comment]
I'm still surprised #127 didn't break CI. @mhazy could you add a test that fails somehow when that happens? Probably just have to make use of `redux-form` somewhere?

**Comment by mhazy** [comment]
@JaKXz No tests currently exist to test those components. There's a task to implement tests with enzyme, I'll discuss with @SethDavenport

**Comment by SethDavenport** [comment]
Yup we need to beef up our automated testing to really have confidence in GK updates.  Jeremy has volunteered to take on the react/enzyme task.

**Comment by SethDavenport** [comment]
Porting the e2e tests from react-redux-starter to the other starters would also go a long way.

**Pull request merged**
