### PR TITLE
upgrade to babel6

### PR DESCRIPTION
**Pull request by andrewdamelio**
### upgrade to babel6
 - Seems like i'm having a issue with getting coverage to run with babel6. any ideas @neilff?

Once the above issue is resolved I think this PR is safe to merge.

### CODE REVIEW

**Comment by andrewdamelio** [comment]
addresses https://github.com/rangle/react-redux-starter/issues/36

**Comment by JaKXz** [comment]
@andrewdamelio et. al if you put a [GitHub keyword](https://help.github.com/articles/closing-issues-via-commit-messages/) in the PR description it will automatically close issues for you :)

**Comment by andrewdamelio** [comment]
@JaKXz Call me old school, but nothing brings me greater joy than manually hitting the Close button on a open issue. :)

**Comment by neilff** [comment]
it looks like it failed CI

**Comment by SethDavenport** [comment]
Looks like an issue with the instanbul setup?

**Comment by SethDavenport** [comment]
I'm going to take this over - I got the coverage working.

**Pull request closed without merging**
