### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by rbrander**
- Added coverage folder to be cleaned
- Updated linting path from . to ./src

### CODE REVIEW

**Comment by rbrander** [comment]
@neilff @SethDavenport Please review

**Comment by SethDavenport** [comment]
I guess this means top-level config files won't be linted?

**Comment by neilff** [comment]
Is lint going into folders you don't want it to go into? If you are trying to avoid a dir, the `.eslintignore` file can take care of that

**Comment by andrewdamelio** [comment]
to @neilff point, in https://github.com/rangle/react-redux-starter/pull/29 i used the ```.eslintignore``` to ignore the coverage folder. I'd prefer to use this method since top level files may need to be linted

**Comment by rbrander** [comment]
The coverage folder was getting linted and causing issues.  I wasn't aware of the ignore file, so I agree, I'll update my PR to use that.

**Comment by rbrander** [comment]
Updated, please review @neilff @andrewdamelio

**Comment by neilff** [comment]
:+1:

**Pull request merged**
